apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: https://github.com/adnan-drina/coolstore-inventory.git
    app.quarkus.io/build-timestamp: ""
    app.quarkus.io/commit-id: ""
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: coolstore-inventory
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: inventory
  namespace: coolstore-inventory-dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/version: 1.0-SNAPSHOT
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
