apiVersion: v1
kind: Service
metadata:
  name: inventory
  namespace: coolstore-inventory-dev
spec:
  ports:
  - name: web
    port: 80
    targetPort: 8080
  - name: metrics
    port: 8080
    targetPort: 8080
  type: ClusterIP
