apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/part-of: coolstore-inventory
    app.kubernetes.io/component: quarkus-service
  name: inventory
  namespace: coolstore-inventory-dev
spec:
  port:
    targetPort: web
  to:
    kind: Service
    name: inventory
