apiVersion: v1
kind: Service
metadata:
  annotations:
    template.openshift.io/expose-uri: postgres://{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}
  labels:
    template: postgresql-ephemeral-template
  name: inventory-database
  namespace: coolstore-inventory-stage
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: inventory-database
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
