apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
      - image: quay.io/adrina/coolstore-inventory:main-85116f0778fdf66006ad2e99cfe63dd390dc6ed6
        imagePullPolicy: Always
        name: inventory
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
