apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app.openshift.io/runtime: quarkus
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"inventory-database"}]'
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/adnan-drina/inventory-catalog.git
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
      - image: quay.io/adrina/coolstore-inventory:main-bceda8ea856e87dda93c2adedff4238c7d4cbc94
        imagePullPolicy: Always
        name: inventory
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
