apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
      - image: quay.io/adrina/coolstore-inventory:main-3252aaaa358211ec13a786167d17cafaa15e7b7a
        imagePullPolicy: Always
        name: inventory
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
