apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 1
  strategy: {}
  template:
    spec:
      containers:
      - image: quay.io/adrina/coolstore-inventory:main-3d8756217d366ee3c87faee462722f3edd0098e8
        imagePullPolicy: Always
        name: inventory
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
