apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    app.openshift.io/connects-to: inventory-database
  labels:
    app.kubernetes.io/name: inventory
    app.kubernetes.io/component: inventory
    app.kubernetes.io/instance: inventory
    app.kubernetes.io/part-of: coolstore-inventory
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: spring
  name: inventory
  namespace: coolstore-inventory-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
      app.kubernetes.io/part-of: coolstore-inventory
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: inventory
        app.kubernetes.io/part-of: coolstore-inventory
    spec:
      containers:
      - image: quay.io/repository/adrina/coolstore-inventory:main-e3d6f36aea3b436921bfb66d35a1ed0802a7994e
        imagePullPolicy: Always
        name: inventory
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
