apiVersion: v1
kind: Service
metadata:
  name: inventory
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
status:
  loadBalancer: {}
