apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: inventory
  name: coolstore-inventory-dev-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: coolstore-inventory-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environments/coolstore-inventory-dev/apps/app-coolstore-inventory/overlays
    repoURL: https://github.com/adnan-drina/coolstore-inventory-gitops.git
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""