kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: coolstore-inventory-source-pvc
  namespace: coolstore-inventory-cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem