apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-env
  namespace: coolstore-inventory-cicd
data:
  ARGOCD_SERVER: openshift-gitops-server-openshift-gitops.apps.cluster-lvtgx.lvtgx.sandbox1743.opentlc.com