apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  creationTimestamp: null
  name: coolstore-inventory-binding
  namespace: coolstore-inventory-cicd
spec:
  params:
  - name: imageRepo
    value: quay.io/adrina/coolstore-inventory
  - name: tlsVerify
    value: "true"
  - name: argoApp
    value: coolstore-inventory-cicd-app
  - name: environmentConfig
    value: environments/coolstore-inventory-stage/apps/app-coolstore-inventory/services/coolstore-inventory/base/config/
status: {}
