apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  creationTimestamp: null
  name: cicd-event-listener
  namespace: coolstore-inventory-cicd
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: github-push-binding
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: webhook-secret-key
          secretName: gitops-webhook-secret
      ref:
        name: github
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'adnan-drina/coolstore-inventory-gitops')
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: ref
      ref:
        name: cel
    name: ci-dryrun-from-push
    template:
      ref: ci-dryrun-from-push-template
  - bindings:
    - ref: coolstore-inventory-binding
    - ref: github-push-binding
    interceptors:
    - params:
      - name: secretRef
        value:
          secretKey: webhook-secret-key
          secretName: webhook-secret-coolstore-inventory-dev-coolstore-inventory
      ref:
        name: github
    - params:
      - name: filter
        value: (header.match('X-GitHub-Event', 'push') && body.repository.full_name
          == 'adnan-drina/coolstore-inventory')
      - name: overlays
        value:
        - expression: body.ref.split('/')[2]
          key: ref
      ref:
        name: cel
    name: app-ci-build-from-push-coolstore-inventory
    template:
      ref: app-ci-template
status:
  configuration:
    generatedName: ""
